- name: Install cadvisor
  become: true
  hosts: all
  vars:
    cadvisor_version: "0.39.3"
    cadvisor_checksum: "sha256:f83194b0563bca7bae536ec68aeb5ead5663d7d4df2e64e660a8a9c80d447d9a"
    cadvisor_options:
      - --docker_only=true
      - --store_container_labels=false

  roles:
    - ansible-cadvisor
