- name: Install cadvisor
  become: true
  hosts: all
  vars:
    cadvisor_version: "0.45.0"
    cadvisor_checksum: "sha256:9a2a0b69f58d932855c0af23b847cb9de8f8c32264f66f9fb5dcc8f359f34ccd"
    cadvisor_options:
      - --docker_only=true
      - --store_container_labels=false

  roles:
    - ansible-cadvisor
