- name: Install cadvisor
  become: true
  hosts: all
  vars:
    cadvisor_version: "0.39.3"
    cadvisor_options:
      - --docker_only=true
      - --store_container_labels=false

  roles:
    - ansible-cadvisor
